apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 21.2.3
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true