apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poweractions
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: 'poweractions'
    repoURL: 'public.ecr.aws/f0z1k7i9' # replace with your GitHub URL
    targetRevision: '*'
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true