apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guessbook
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'tree/master/helm-guestbook'
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - https://github.com/argoproj/argocd-example-apps/blob/master/helm-guestbook/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true