apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: 'stable/mysql'
    repoURL: 'https://charts.helm.sh/stable'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true